### ISSUE TITLE
no testure for weapons and crash pressing skill button without skill

### ISSUE THREAD

**Issue by Joshernoob** [Forixaim/Epic-Fight-Battle-Styles#11]
![Screenshot 2024-05-16 183138](https://github.com/Forixaim/Epic-Fight-Battle-Styles/assets/64944433/fb6d550b-b1ab-49dd-9d02-60c546ea7336)
![2024-05-16_18 05 17](https://github.com/Forixaim/Epic-Fight-Battle-Styles/assets/64944433/ad8c5959-2bf8-41b0-82df-0346d7afca24)

Pictures for ref

forge latest version 
epic fight latest version
this mod latest version

**Comment by Forixaim** [comment]
those shouldn't be used at the moment since the weapons are not really implemented yet.
