### ISSUE TITLE
Incompat with Kingdom Keys 2

### ISSUE THREAD

**Issue by RoweJN** [Forixaim/Epic-Fight-Battle-Styles#5]
So I'm running a modpack with 200+ mods that all run fine except that it appears epic fight Battle Styles and the Kingdom Keys 2 mod don't play well with each other. If one of these mods is removed then I can run the game just fine, but with both of them minecraft will crash the moment I attempt to load into a world.

Minecraft Version: 1.20.1
Forge Version: 1.20.1 - 47.2.20
Epic Fight Version: 20.6.3
Epic Fight Battle Styles Version: 1.0.2.1-1.20.1
[crash-2024-01-27_10.17.43-client.txt](https://github.com/Forixaim/Epic-Fight-Battle-Styles/files/14073336/crash-2024-01-27_10.17.43-client.txt)

**Comment by Forixaim** [comment]
Thanks, I'll run it with Kingdom Keys 2 then I will let you know.

I have been really busy with irl stuff but since it's the weekend I'm able to help a bit.
