### ISSUE TITLE
1.19.2 forge invalid datapack cuz efm update and pee on code again like why tf does efm always change the code so that any addon just doesn't fucking work (sorry for rant im not actually mad at the crash its just that efm does this way too much)

### ISSUE THREAD

**Issue by loti1234** [Forixaim/Epic-Fight-Battle-Styles#7]
[2024-03-05-3.log](https://github.com/Forixaim/Epic-Fight-Battle-Styles/files/14497385/2024-03-05-3.log)

[crash-2024-03-05_16.03.14-client.txt](https://github.com/Forixaim/Epic-Fight-Battle-Styles/files/14497396/crash-2024-03-05_16.03.14-client.txt)

**Comment by Forixaim** [comment]
1.19.2's update has been on pause due to lack of people playing it.

But issues are issues, and I am here to fix them.

I will fix any issues but new features wont be coming until a really major change releases on 1.20.1.
