### ISSUE TITLE
Weapons of Miracles movesets break

### ISSUE THREAD

**Issue by Loonard** [Forixaim/Epic-Fight-Battle-Styles#8]
Version: 1.20.1
Forge: 47.2.20
EF: 20.7.4
BattleStyles: 1.0.3-1.20.1

Installing the mod breaks weapons of miracles movesets. As far as I understand, it locks up Satsujin and Sword and Shield movesets behind style requirements of Demon and Atlantean. However, learning those styles DOES NOT fix the weapons. They keep being treated like Uchigatana and Sword + Shield with no special moveset.

**Comment by Forixaim** [comment]
I'm removing the movesets and later removing the datapacks, thanks for reaching out.
