### ISSUE TITLE
Can't load Epic Fight for 1.20.1 (with a compat mod for the same version)

### ISSUE THREAD

**Issue by LilyPettle** [Forixaim/Epic-Fight-Battle-Styles#9]
Hi! Really want to make a modpack for me and my friends to play around on partially using this mod, but when I try to launch any of the 1.20.1 compatible versions through modrinth it simply says the forge version is too old, even though it's the latest forge model for 1.20.1. I feel like that's not right since there are older and newer version compatibilities. Does it have to be 1.20.2? I feel like there's not enough mods in that version for a modpack, and using an older version requires me to nix its compatibility mod for Expanded Combat, and Epic Fight Battle Styles. If I switch to newer version it'll literally just be this mod and nothing else, is there anyway to get it to work?

Minecraft version 1.20.1
Forge version 47.2.17
"Mod epicfight requires forge 47.2.20 or above
Currently, forge is 47.2.17"

**Comment by LilyPettle** [comment]
Sorry I forgot mod version, its 20.6.5 (I picked the compatible one with the most downloads in attempt to get it to work)

**Comment by Forixaim** [comment]
Use the latest update, there has been a lot of changes as of recently.
